interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x20000
  rodata:
    base_addr: 0x8014000
    file: uEmu.3Dprinter.bin
    file_offset: 0x14000
    permissions: r--
    size: 0x3000
  text:
    base_addr: 0x8000000
    file: uEmu.3Dprinter.bin
    permissions: r-x
    size: 0x14000
  zero:
    base_addr: 0x0
    permissions: rw-
    size: 0x1000
mmio_models:
  bitextract:
    pc_08001d64_mmio_40004404:
      access_size: 0x4
      addr: 0x40004404
      left_shift: 0x0
      mask: 0xff
      pc: 0x8001d64
      size: 0x1
  constant:
    pc_08000a52_mmio_4227810c:
      access_size: 0x4
      addr: 0x4227810c
      pc: 0x8000a52
      val: 0x0
  passthrough:
    pc_08000956_mmio_40013c08:
      access_size: 0x4
      addr: 0x40013c08
      init_val: 0x0
      pc: 0x8000956
    pc_08000ed2_mmio_40010800:
      access_size: 0x4
      addr: 0x40010800
      init_val: 0x0
      pc: 0x8000ed2
    pc_08001c62_mmio_40013810:
      access_size: 0x4
      addr: 0x40013810
      init_val: 0x0
      pc: 0x8001c62
  set:
    pc_08001b04_mmio_40004400:
      access_size: 0x4
      addr: 0x40004400
      pc: 0x8001b04
      vals:
      - 0x0
      - 0x80
nvic:
  disabled_irqs:
  - 0x13
